# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-08-05 02:07
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='detail',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='商品详情'),
        ),
    ]
